name: CD

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: yarn install
    - run: |
        git config --local user.email "git@phoqe.dev"
        git config --local user.name "Linus Långberg"
    - run: yarn deploy
    env:
      GIT_USER: phoqe
